version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./backend/mongo-data:/data/db
      - ./mongo-dump:/docker-entrypoint-initdb.d
  backend:
    build: ./backend
    container_name: bolivialudica-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./backend/uploads:/app/uploads
  frontend:
    build: ./frontend
    container_name: bolivialudica-frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend