// Este archivo exporta el array de departamentos para ser usado en ComunidadTienda.jsx
const departamentos = [
	{
		nombre: 'Cochabamba',
		ambiente: '/Bolivia-ludica/assets/image/ambientes/Cochabamba/Antikuna/Antikuna.jpg',
		tiendas: [
			{
				nombre: 'Antikuna',
				logo: '/Bolivia-ludica/assets/image/stores/antikuna.png',
				ciudad: 'Cochabamba',
				especialidad: 'General',
				descripcion: 'Juegos y entretenimiento para todos',
				direccion: 'Av. Juan de la Rosa # 256, Cochabamba, Bolivia',
				telefono: 'N/A',
				email: '',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/antikunacafe/',
					instagram: 'https://www.instagram.com/antikunaboardgamecafe/',
					tiktok: ''
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: [
					'/Bolivia-ludica/assets/image/ambientes/Cochabamba/Antikuna/Antikuna.jpg',
					'/Bolivia-ludica/assets/image/ambientes/Cochabamba/Antikuna/Antikuna2.jpg'
				],
			},
			{
				nombre: 'El Mercader Errante',
				logo: '/Bolivia-ludica/assets/image/stores/mercadererrante.jpg',
				ciudad: 'Cochabamba',
				especialidad: 'Mesa y Rol',
				descripcion: 'Juegos de mesa y rol',
				direccion: 'Dirección no disponible',
				telefono: '72219585',
				email: 'juancvc_1@hotmail.com',
				web: 'https://magicgamesbolivia.com/',
				redes: {
					facebook: 'juancvc_1@hotmail.com',
					instagram: 'https://www.instagram.com/magicgamesbolivia/',
					tiktok: 'https://www.tiktok.com/@magicgamesbolivia'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Cochabamba/MercadoErrante/MercadoErrante.jpg',
			},
			{
				nombre: 'Tinkuna Games',
				logo: '/Bolivia-ludica/assets/image/stores/tinkunagmaes.png',
				ciudad: 'Cochabamba',
				especialidad: 'General',
				descripcion: 'Juegos de mesa y eventos especiales',
				direccion: 'Dirección no disponible',
				telefono: '77958996',
				email: 'elpobladobtg@gmail.com',
				web: 'https://sites.google.com/view/catalogo-tinkuna-games/productos',
				redes: {
					facebook: 'https://www.facebook.com/people/El-Poblado/61562278854386/',
					instagram: 'https://www.instagram.com/elpobladobtg/',
					tiktok: 'https://www.tiktok.com/@el.poblado.by.tin'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Cochabamba/Tinkunagames/TinkunaGames.jpg',
			},
			{
				nombre: 'Games Landing',
				logo: '/Bolivia-ludica/assets/image/stores/gameslanding.jpg',
				ciudad: 'Cochabamba',
				especialidad: 'General',
				descripcion: 'Tu destino para juegos de mesa',
				direccion: 'Dirección no disponible',
				telefono: '74570507',
				email: 'info@gameslanding.com',
				web: 'https://gameslanding.com/',
				redes: {
					facebook: 'https://www.facebook.com/GamesLanding/',
					instagram: 'https://www.instagram.com/gameslanding.bo/',
					tiktok: 'https://www.tiktok.com/@gameslandingbo'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Cochabamba/GamesLanding/GamesLanding.jpg',
			},
			{
				nombre: 'Magic Games',
				logo: '/Bolivia-ludica/assets/image/stores/magicgames.jpg',
				ciudad: 'Cochabamba',
				especialidad: 'Magic: The Gathering',
				descripcion: 'Especialistas en Magic: The Gathering',
				direccion: 'Dirección no disponible',
				telefono: 'N/A',
				email: 'N/A',
				web: '#',
				redes: {
					facebook: '',
					instagram: '',
					tiktok: ''
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: [
					'/Bolivia-ludica/assets/image/ambientes/Cochabamba/MagicgGames/IMG-20241014-WA0053.jpg',
					'/Bolivia-ludica/assets/image/ambientes/Cochabamba/MagicgGames/IMG-20241014-WA0054.jpg'
				],
			},
		],
	},
	{
		nombre: 'La Paz',
		ambiente: '/Bolivia-ludica/assets/image/ambientes/LaPaz/GuaridadelGoblin/GuaridadelGoblin.jpg',
		tiendas: [
			{
				nombre: 'Bros Game Club',
				logo: '/Bolivia-ludica/assets/image/stores/brosGame.png',
				ciudad: 'La Paz',
				especialidad: 'General',
				descripcion: 'Comunidad activa de juegos de mesa y TCG',
				direccion: "Av Hernando Siles entre calles 1 y 2, Edificio 'Señor de la Exaltación' local 1 (ex Space Food) No 4683, Obrajes, La Paz, Bolivia",
				telefono: '78252090',
				email: 'bro@bro-s.club',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/brosgameclub/',
					instagram: 'https://www.instagram.com/brosgameclub/'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/LaPaz/Bros/Bros.jpg',
			},
			{
				nombre: 'Guarida del Goblin',
				logo: '/Bolivia-ludica/assets/image/stores/guaridadelgoblin.png',
				ciudad: 'La Paz',
				especialidad: 'Rol y Miniaturas',
				descripcion: 'Especialistas en juegos de rol y miniaturas',
				direccion: 'Dirección no disponible',
				telefono: 'N/A',
				email: 'N/A',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/people/La-Guarida-del-Goblin/100063749131951/',
					instagram: 'https://www.instagram.com/laguaridadelgoblin/',
					tiktok: 'https://www.tiktok.com/@guaridadelgoblin'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/LaPaz/GuaridadelGoblin/GuaridadelGoblin.jpg',
			},
			{
				nombre: 'Shadow Games',
				logo: '/Bolivia-ludica/assets/image/stores/shadowgame.jpg',
				ciudad: 'La Paz',
				especialidad: 'Estrategia',
				descripcion: 'Tu destino para juegos de estrategia',
				direccion: 'Dirección no disponible',
				telefono: '62328866',
				email: 'shadowgamesbol@gmail.com',
				web: 'https://shadowgamesbo.com/',
				redes: {
					facebook: 'https://www.facebook.com/shadowgamesbo/',
					instagram: 'https://www.instagram.com/shadow_gamesbo/',
					tiktok: 'https://www.tiktok.com/@shadowgamesbo'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/LaPaz/ShadowGames/ShadowGames.jpg',
			},
		],
	},
	{
		nombre: 'Oruro',
		ambiente: '/Bolivia-ludica/assets/image/ambientes/Oruro/CoffeArkham/CoffeArkham.jpg',
		tiendas: [
			{
				nombre: 'Coffe Arkham',
				logo: '/Bolivia-ludica/assets/image/stores/coffearkham.jpg',
				ciudad: 'Oruro',
				especialidad: 'Café y Juegos',
				descripcion: 'Café y juegos en un ambiente único',
				direccion: 'Dirección no disponible',
				telefono: 'N/A',
				email: 'N/A',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/coffee.arkham',
					instagram: '',
					tiktok: ''
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Oruro/CoffeArkham/CoffeArkham.jpg',
			},
			{
				nombre: 'Dados y Dragones',
				logo: '/Bolivia-ludica/assets/image/stores/dadosydragones.jpg',
				ciudad: 'Oruro',
				especialidad: 'Rol y Mesa',
				descripcion: 'Juegos de rol y mesa en un ambiente acogedor',
				direccion: 'Montecinos y Soria Galvarro, Oruro, Bolivia',
				telefono: '75704175',
				email: 'gobajuegos@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/dadosydragonesbo/',
					instagram: '',
					tiktok: ''
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Oruro/DadosYDragones/DadosYDragones.jpg',
			},
			{
				nombre: 'El baúl de los juegos',
				logo: '/Bolivia-ludica/assets/image/stores/bauldejuegos.jpg',
				ciudad: 'Oruro',
				especialidad: 'General',
				descripcion: 'Gran variedad de juegos clásicos y modernos',
				direccion: 'Pagador entre León y Rodríguez, Oruro, Bolivia',
				telefono: '76142380',
				email: 'N/A',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/ElBaulDeLosJuegos01/',
					instagram: '',
					tiktok: 'https://www.tiktok.com/@baul.de.los.juegos'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Oruro/BauldelosJuegos/BauldelosJuegos.jpg',
			},
			{
				nombre: 'La posada del gato',
				logo: '/Bolivia-ludica/assets/image/stores/posadadelgato.png',
				ciudad: 'Oruro',
				especialidad: 'General',
				descripcion: 'Juegos y comunidad en un espacio único',
				direccion: 'Avenida del Valle y Calle 4 , Oruro, Bolivia',
				telefono: '62789462',
				email: 'laposadadelgato.4@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/people/La-Posada-Del-Gato/61561165382629/',
					instagram: '',
					tiktok: 'https://www.tiktok.com/@la_posada_del_gato_oruro'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Oruro/PosadaDelGato/PosadaDelGato.jpg',
			},
		],
	},
	{
		nombre: 'Potosí',
		ambiente: '/Bolivia-ludica/assets/image/ambientes/Potosi/LeGato/LeGato.jpg',
		tiendas: [
			{
				nombre: 'Le gato',
				logo: '/Bolivia-ludica/assets/image/stores/legato.jpg',
				ciudad: 'Potosí',
				especialidad: 'General',
				descripcion: 'Juegos y diversión para todos',
				direccion: 'Dirección no disponible',
				telefono: '70461652',
				email: 'jhontitorjontitor.f@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/people/Le-Gato-Ludo-Club/61564192205114/',
					instagram: '',
					tiktok: ''
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Potosi/LeGato/LeGato.jpg',
			},
		],
	},
	{
		nombre: 'Santa Cruz',
		ambiente: '/Bolivia-ludica/assets/image/ambientes/SantaCruz/JugateEsta/JugateEsta.jpg',
		tiendas: [
			{
				nombre: 'Sharks TCG',
				logo: '/Bolivia-ludica/assets/image/stores/sharkstcg.jpg',
				ciudad: 'Santa Cruz',
				especialidad: 'Juegos de cartas coleccionables',
				descripcion: 'Especialistas en juegos de cartas coleccionables',
				direccion: 'Calle Buenos Aires No. 142 Planta Alta',
				telefono: '73248263',
				email: 'N/A',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/sharkstcg',
					instagram: 'https://www.instagram.com/sharks_tcg/'
				},
				horario: { 'Lun–Sab': '10:00–20:00' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/SantaCruz/SharksTCG/SharksTCG.jpg',
			},
			{
				nombre: 'La Mazmorra del Juasi',
				logo: '/Bolivia-ludica/assets/image/stores/juasi.jpg',
				ciudad: 'Santa Cruz',
				especialidad: 'General',
				descripcion: 'Juegos de mesa y eventos comunitarios',
				direccion: 'Dr. Leonor Ribera Arteaga 3360, Santa Cruz de la Sierra, Bolivia',
				telefono: '69038332',
				email: 'Monrroysamanta@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/LamazmorradelJausi/',
					instagram: 'https://www.instagram.com/lamazmorradeljausi/',
					tiktok: 'https://www.tiktok.com/@lamazmorradeljausi'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/SantaCruz/Jausi/Jausi.jpg',
			},
			{
				nombre: 'Uruloki',
				logo: '/Bolivia-ludica/assets/image/stores/uroloki.jpg',
				ciudad: 'Santa Cruz',
				especialidad: 'General',
				descripcion: 'Variedad de juegos y torneos semanales',
				direccion: '21 de Mayo y Florida, Santa Cruz de la Sierra, Bolivia',
				telefono: '72620510',
				email: 'urulokiscz@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/people/Urul%C3%B3ki/100064057929678/'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/SantaCruz/Uruloki/Uruloki.jpg',
			},
			{
				nombre: 'Jugate Esta',
				logo: '/Bolivia-ludica/assets/image/stores/jugateesta.jpg',
				ciudad: 'Santa Cruz',
				especialidad: 'Familiar',
				descripcion: 'Juegos para toda la familia',
				direccion: 'Calle Ñuflo de Chavez #617 3er piso , Santa Cruz de la Sierra, Bolivia',
				telefono: '77669066',
				email: 'jugateesta@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/JugateEsta/',
					instagram: 'https://www.instagram.com/jugateesta_bo/'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/SantaCruz/JugateEsta/JugateEsta.jpg',
			},
		],
	},
	{
		nombre: 'Sucre',
		ambiente: '/Bolivia-ludica/assets/image/ambientes/Sucre/PuntoDeVictoria/PuntoDeVictoria.jpg',
		tiendas: [
			{
				nombre: 'Punto de Victoria',
				logo: '/Bolivia-ludica/assets/image/stores/puntodevictoria.jpg',
				ciudad: 'Sucre',
				especialidad: 'General',
				descripcion: 'Juegos de mesa y comunidad activa',
				direccion: 'Dirección no disponible',
				telefono: '61892074',
				email: 'puntodevictoriasucre@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/people/Punto-de-Victoria/100093685569540/',
					instagram: '',
					tiktok: 'https://www.tiktok.com/@puntodevictoria_sucre'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Sucre/PuntoDeVictoria/PuntoDeVictoria.jpg',
			},
		],
	},
	{
		nombre: 'Tarija',
		ambiente: '/Bolivia-ludica/assets/image/ambientes/Tarija/Bazinga/Bazinga.jpg',
		tiendas: [
			{
				nombre: 'Bazinga',
				logo: '/Bolivia-ludica/assets/image/stores/bazinga.jpg',
				ciudad: 'Tarija',
				especialidad: 'General',
				descripcion: 'Juegos de mesa y entretenimiento',
				direccion: 'C/ Avaroa E/ Suipacha y Mendez, Ciudad Tarija, Bolivia',
				telefono: '78706666',
				email: 'bazingacafeludico@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/people/Bazinga-Caf%C3%A9-L%C3%BAdico/61551852961559/',
					instagram: '',
					tiktok: ''
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Tarija/Bazinga/Bazinga.jpg',
			},
			{
				nombre: 'Mesa Dragon',
				logo: '/Bolivia-ludica/assets/image/stores/mesadragon.jpg',
				ciudad: 'Tarija',
				especialidad: 'General',
				descripcion: 'Juegos de mesa y eventos especiales',
				direccion: 'C. Felix Soto entre C. Bernardo Raña Trigo y C. Juan José Cortez, Tarija, Bolivia',
				telefono: '76187558',
				email: 'mesadragontja@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/MesaDragonTja/',
					instagram: 'https://www.instagram.com/mesadragontja/',
					tiktok: ''
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '/Bolivia-ludica/assets/image/ambientes/Tarija/MesaDragon/MesaDragon.jpeg',
			},
			{
				nombre: 'Mini Toys',
				logo: '/Bolivia-ludica/assets/image/stores/minitoys.jpg',
				ciudad: 'Tarija',
				especialidad: 'General',
				descripcion: 'Juegos para todas las edades',
				direccion: 'Calle 15 de Abril #234 entre Méndez y Suipacha, Tarija, Bolivia',
				telefono: '61856234',
				email: 'minitoystarija@gmail.com',
				web: '#',
				redes: {
					facebook: 'https://www.facebook.com/minitoystarija/',
					instagram: 'https://www.instagram.com/minitoystarija',
					tiktok: ''
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '',
			},
			{
				nombre: 'Caja de Juegos',
				logo: '/Bolivia-ludica/assets/image/stores/cajadejuegos.jpg',
				ciudad: 'Tarija',
				especialidad: 'General',
				descripcion: 'Tu tienda local de juegos',
				direccion: 'Dirección no disponible',
				telefono: '74535305',
				email: 'Cajadejuegosad@gmail.com',
				web: 'https://lacajadejuegos.com/',
				redes: {
					facebook: 'https://www.facebook.com/people/La-caja-de-juegos/61557443236887/',
					instagram: 'https://www.instagram.com/lacajadejuegosbolivia/',
					tiktok: 'https://www.tiktok.com/@lacajadejuegos'
				},
				horario: { 'Horario': 'Horario no disponible' },
				juegos: [],
				eventos: [],
				ambiente: '',
			},
		],
	},
];

export default departamentos;
