// Archivo de productos para importar en Tienda y ProductoDetalle
const productos = [
  {
    nombre: 'Combo Juegos de Mesa y Cartas',
    precio: 'Bs 250',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Antikuna',
    departamento: 'Cochabamba',
  },
  {
    nombre: 'Set de Cartas Premium',
    precio: 'Bs 80',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'El Mercader Errante',
    departamento: 'Cochabamba',
  },
  {
    nombre: 'Ajedrez Profesional',
    precio: 'Bs 120',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Tinkuna Games',
    departamento: 'Cochabamba',
  },
  {
    nombre: 'Kit Monopoly Familiar',
    precio: 'Bs 180',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Games Landing',
    departamento: 'Cochabamba',
  },
  {
    nombre: 'Dados y Accesorios',
    precio: 'Bs 35',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Magic Games',
    departamento: 'Cochabamba',
  },
  {
    nombre: 'Póker Set Completo',
    precio: 'Bs 150',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Bros Game Club',
    departamento: 'La Paz',
  },
  {
    nombre: 'Tablero Clásico de Damas',
    precio: 'Bs 60',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Guarida del Goblin',
    departamento: 'La Paz',
  },
  {
    nombre: 'Colección Juegos Familiares',
    precio: 'Bs 320',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Shadow Games',
    departamento: 'La Paz',
  },
  {
    nombre: 'Set Clásico de Cartas',
    precio: 'Bs 70',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Coffe Arkham',
    departamento: 'Oruro',
  },
  {
    nombre: 'Juegos de Rol Básicos',
    precio: 'Bs 200',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Dados y Dragones',
    departamento: 'Oruro',
  },
  {
    nombre: 'Baúl de Juegos',
    precio: 'Bs 180',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'El baúl de los juegos',
    departamento: 'Oruro',
  },
  {
    nombre: 'Pack Familiar de Damas',
    precio: 'Bs 90',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'La posada del gato',
    departamento: 'Oruro',
  },
  {
    nombre: 'Set de Estrategia',
    precio: 'Bs 110',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Le gato',
    departamento: 'Potosí',
  },
  {
    nombre: 'Juegos de Mesa Kids',
    precio: 'Bs 130',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Jugate esta',
    departamento: 'Santa Cruz',
  },
  {
    nombre: 'Mazmorra y Aventuras',
    precio: 'Bs 210',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'La Mazmorra del Juasi',
    departamento: 'Santa Cruz',
  },
  {
    nombre: 'Cartas TCG Pro',
    precio: 'Bs 160',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Sharks TCG',
    departamento: 'Santa Cruz',
  },
  {
    nombre: 'Set Dragón',
    precio: 'Bs 140',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Uruloki',
    departamento: 'Santa Cruz',
  },
  {
    nombre: 'Victoria Total',
    precio: 'Bs 170',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Punto de Victoria',
    departamento: 'Sucre',
  },
  {
    nombre: 'Bazinga Party',
    precio: 'Bs 200',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Bazinga',
    departamento: 'Tarija',
  },
  {
    nombre: 'Mesa Dragon Deluxe',
    precio: 'Bs 300',
    imagen: '/Bolivia-ludica/assets/image/boardgame.jpeg',
    tienda: 'Mesa Dragon',
    departamento: 'Tarija',
  },
];

export default productos;
