// Archivo de productos para importar en Tienda y ProductoDetalle
const productos = [
  {
    nombre: 'Bolígrafo',
    precio: 'Bs 10',
    imagen: '/Bolivia-ludica/assets/image/productos/boligrafo.webp',
    tiendas: ['Bolivia Lúdica', 'Antikuna'],
    departamentos: ['Cochabamba', 'La Paz'],
    categoria: ['Accesorios'],
    badge: 'Nuevo',
  },
  {
    nombre: 'Bolsa',
    precio: 'Bs 20',
    imagen: '/Bolivia-ludica/assets/image/productos/bolsas.webp',
    tiendas: ['Bolivia Lúdica', 'Magic Games'],
    departamentos: ['Cochabamba', 'Oruro'],
    categoria: ['Accesorios'],
    badge: 'Popular',
  },
  {
    nombre: 'Camiseta',
    precio: 'Bs 150',
    imagen: '/Bolivia-ludica/assets/image/productos/camiseta.webp',
    tiendas: ['Bolivia Lúdica'],
    departamentos: ['Cochabamba'],
    categoria: ['Ropa'],
    badge: 'En oferta',
  },
  {
    nombre: 'Case',
    precio: 'Bs 35',
    imagen: '/Bolivia-ludica/assets/image/productos/case.webp',
    tiendas: ['Bolivia Lúdica', 'Shadow Games'],
    departamentos: ['Cochabamba', 'La Paz'],
    categoria: ['Accesorios'],
    badge: 'Nuevo',
  },
  {
    nombre: 'Gorra',
    precio: 'Bs 40',
    imagen: '/Bolivia-ludica/assets/image/productos/gorra.webp',
    tiendas: ['Bolivia Lúdica', 'Jugate esta'],
    departamentos: ['Cochabamba', 'Santa Cruz'],
    categoria: ['Ropa'],
    badge: 'Popular',
  },
  {
    nombre: 'Popsocket',
    precio: 'Bs 15',
    imagen: '/Bolivia-ludica/assets/image/productos/popsocket.webp',
    tiendas: ['Bolivia Lúdica'],
    departamentos: ['Cochabamba'],
    categoria: ['Accesorios'],
    badge: 'En oferta',
  },
  {
    nombre: 'Taza',
    precio: 'Bs 25',
    imagen: '/Bolivia-ludica/assets/image/productos/taza.webp',
    tiendas: ['Bolivia Lúdica', 'Guarida del Goblin'],
    departamentos: ['Cochabamba', 'La Paz'],
    categoria: ['Accesorios'],
    badge: 'Nuevo',
  },
  {
    nombre: 'Tomatodo',
    precio: 'Bs 40',
    imagen: '/Bolivia-ludica/assets/image/productos/tomatodo.webp',
    tiendas: ['Bolivia Lúdica', 'Mesa Dragon'],
    departamentos: ['Cochabamba', 'Tarija'],
    categoria: ['Accesorios'],
    badge: 'Popular',
  },
  {
    nombre: 'Totebag',
    precio: 'Bs 35',
    imagen: '/Bolivia-ludica/assets/image/productos/totebag.webp',
    tiendas: ['Bolivia Lúdica', 'Bazinga'],
    departamentos: ['Cochabamba', 'Tarija'],
    categoria: ['Accesorios'],
    badge: 'En oferta',
  },
];

export default productos;
